apiVersion: apps/v1
kind: Deployment
metadata:
  name: brighterbee-category-api-deployment
spec:
  strategy:
    type: RollingUpdate      
  replicas: 1
  selector:
    matchLabels:
      app: brighterbee-api
      name: category-service-api
  template:
    metadata:
      name: category-pod
      labels:
        app: brighterbee-api
        name: category-service-api
    spec:
      containers:
        - name: category-service-container          
          image: patilashwin/brighterbee-category-service:1.7
          ports:
            - name: serverport
              containerPort: 8000
          livenessProbe:            
            httpGet:
              port: serverport
              path: /actuator/health/liveness
              scheme: HTTP
          readinessProbe:
            httpGet:
              port: serverport
              path: /actuator/health/readiness
              scheme: HTTP
          volumeMounts:
            - name: config-vol
              mountPath: /vol-mnt
            - name: vol-pd
              mountPath: /vol-tst
      volumes:
        - name: config-vol
          configMap:
            name: brighterbee-category-service
        - name: vol-pd
          gcePersistentDisk:
              pdName: mysql-persistent-disk
              fsType: ext4
---
apiVersion: v1
kind: Service
metadata:
  name: category-service
spec:
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 32648
  selector:
    app: brighterbee-api
    name: category-service-api